redirectsOrigin = "config"
plugins = []
functionsDirectory = "/Users/zhangzhu/WorkBuddy/20260425205635/caviar_crm_app/frontend/netlify/functions"
functionsDirectoryOrigin = "config"
headers = []

[functions]

[functions."*"]

[build]
publish = "/Users/zhangzhu/WorkBuddy/20260425205635/caviar_crm_app/frontend/dist"
publishOrigin = "config"
commandOrigin = "config"
command = "cd frontend && npm run build"
functions = "/Users/zhangzhu/WorkBuddy/20260425205635/caviar_crm_app/frontend/netlify/functions"

[build.environment]
NODE_VERSION = "18"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]